name: ballotpal
dependencies:
  - python=3.11
  - pip=23.0.1
  - pip:
      - pytest==7.2.1
      - pytest-mock==3.2.0
      - pytest-cov==2.10.0
      - numpy==1.24.2
      - openai==0.27.0
      - pandas==1.5.3
      - tiktoken==0.2.0
      - beautifulsoup4==4.11.2
      - google-cloud-translate==3.11.0
